### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai201-bogachik#11]
https://drive.google.com/file/d/1JyDN82JcLyx0T7sfTc0DpPWHgLITt2Rg/view?usp=sharing

**Comment by kovasnik** [comment]
Завдання 1 
Сон 
Для споживача є зрозумілим потреба у сні.
Для споживача інфорцація про сон є цінною для розпорядження ним.
Для споживача інформація про сон є актальною так як сон є важливою складовою.

Завдання 2
"Авторизація користувача" забезпечує можливість увійти до додатку та користуватися його функціями що наближає нас до стабільної інженерної діяльності.

"Перегляд та запис даних про свій сон" забезпечує корректну інформацію про свій сон яка наближує нас до стабільного сну.

"Отрримувати корисну інформацію про розпорядок дня" забезпечує інформацією що може покращити емоційно-психологічне здоров'я під час роботи.

**Comment by oleksandrblazhko** [comment]
Оцінка = 3 бали
